version: '3'

services:
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi:2.0.0
    environment:
      - TZ=America/Montreal    # By default container with Montreal tyme zone (change if neccesary. )
      - NIFI_WEB_HTTP_HOST=nifi
      - SINGLE_USER_CREDENTIALS_USERNAME=nifi-projet123   # You can change for desired user
      - SINGLE_USER_CREDENTIALS_PASSWORD=nifi-projet123   # You can change for desired password
      
    container_name: nifi
    ports:
    # Check if you need to changes the port before the colon ":"
      - "58081:8080/tcp" # HTTP interface.   
      - "8443:8443/tcp" # HTTPS interface
      - "514:514/tcp" # Syslog
      - "514:514/udp" # Syslog
      - "2055:2055/udp" # NetFlow
    volumes:
    # Check the persistent volumes names are not equal to any docker previous installation
      - nifi-drivers:/opt/nifi/nifi-current/drivers   
      - nifi-certs:/opt/certs
      - nifi-conf:/opt/nifi/nifi-current/conf
    # Copy postgresql driver in container.     
      - ./postgresql-42.7.4.jar:/opt/nifi/nifi-current/drivers/postgresql-42.7.4.jar
      
    restart: unless-stopped

volumes:
  nifi-drivers:
    name: nifi-drivers
  nifi-certs:
    name: nifi-certs
  nifi-conf:
    name: nifi-conf